### PR TITLE
Type Definition Changes - Fixes #429

### LINKED ISSUE #429: typings index.d.ts failing transpilation, needs an ts-ignore bypass.
Using @vonage/server-sdk with typescript doesn't transpile without an unrecommended bypass, but then it doesn't work at all.

## Expected Behavior
The expected behavior is to use the package without ts notations

## Current Behavior
The current behavior is the next.
```typescript
import * as Vonage from '@vonage/server-sdk';
const nexmo = new Vonage({
      apiKey: 'asdf',
      apiSecret: 'asdf',
    });
// throws:
// TS2351: This expression is not constructable.
// Type 'typeof import("@vonage/server-sdk")' has no construct signatures
```
  
```typescript
import Vonage from '@vonage/server-sdk';
const nexmo = new Vonage({
      apiKey: 'asdf',
      apiSecret: 'asdf',
    });
// ide don't complain, but when executing the bundle it throws a fatal error:
// TypeError: server_sdk_1.default is not a constructor
```

## Context
Now it needs to be used with this ts notations:
```typescript
import * as Vonage from '@vonage/server-sdk';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
const nexmo = new Vonage({
      apiKey: 'asdf',
      apiSecret: 'asdf',
    });
const from = 'Vonage APIs';
const to = '...';
const text = 'Hello from Vonage SMS API';

nexmo.message.sendSms(from, to, text, {}, (err, data) => {
   console.log(err);
   console.log(data);
});
// sms received
```

## Your Environment
* SDK Version:  "2.10.4"
* Node Version: v14.15.1
* TSC Version: 4.0.3
* Operating System and version: Ubuntu 20.04.1 LTS

### PR DESCRIPTION
**Pull request by kellyjandrews**
## Description
Users are having issues with the types definition and imports of module types. 

## Motivation and Context

Addresses #429

## Testing Details

Changes were tested using a typescript project to validate that imports worked properly and types were accurate.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: typings/index.d.ts [hunk 1]
```diff
@@ -1,598 +1,600 @@
...
+	[key: string]: any;
+}
+
+
+export default class Vonage {
+	credentials: CredentialsObject;
+	options: VonageOptions;
+
+	constructor(credentials: CredentialsObject, options?: { [key: string]: any });
+	message: Message
```
Comment (michaeljolley) [inline typings/index.d.ts]: Looks like we're missing a few here. `verify`, `media`, etc.

Comment (kellyjandrews) [reply typings/index.d.ts]: Thanks - added them back in.

**Review by michaeljolley — APPROVED** [review]
